### ISSUE TITLE
Demo app at http://bmorton.co.uk/angular doesn't work

### ISSUE THREAD

**Issue by martinsik** [BTMorton/angular2-grid#23]
Hey, the demo app doesn't work because it tries to load [http://bmorton.co.uk/angular/app](http://bmorton.co.uk/angular/app) and the server responses with some CSS styles. You can see it in developer tools:
```css
.grid-item {
	border: solid 1px;
}

.handle {
	width: 100%;
	height: 50px;
	background: blue;
}
```

However, when opened in the browser it serves some HTML template.
